server:
  # from config is 8181
  port: 8180
spring:
  application:
    name: skt-ms-gateway
  cloud:
    gateway:
      routes:
        - id: skt-ms-tester
          uri: lb://skt-ms-tester
          predicates:
            - Path=/skt-ms-tester/**
          filters:
            - RewritePath=/skt-ms-tester/(?<path>.*), /$\{path}
        - id: skt-ms-auth
          uri: http://localhost:8080
          predicates:
            - Path=/skt-ms-auth/**
          filters:
            - RewritePath=/skt-ms-auth/(?<path>.*), /$\{path}
        - id: skt-ms-user
          uri: lb://skt-ms-user
          predicates:
            - Path=/skt-ms-user/**
          filters:
            - RewritePath=/ms-user/(?<path>.*), /$\{path}
        - id: skt-ms-product
          uri: lb://skt-ms-product
          predicates:
              - Path=/skt-ms-product/**
          filters:
              - RewritePath=/skt-ms-product/(?<path>.*), /$\{path}
        - id: skt-ms-cloth
          uri: lb://skt-ms-cloth
          predicates:
              - Path=/skt-ms-cloth/**
          filters:
              - RewritePath=/skt-ms-cloth/(?<path>.*), /$\{path}
        - id: skt-ms-order
          uri: lb://skt-ms-order
          predicates:
              - Path=/skt-ms-order/**
          filters:
              - RewritePath=/skt-ms-order/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: gateway
eureka:
  config:
    import: optional:file:.env[.properties]
  client:
    enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8707/eureka/}